################################################################################
#
#   ORGANIZATIONS
#
#   This section defines the organizational identities that can be referenced
#   in the configuration profiles.
#
################################################################################
Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ../artifacts/crypto-config/ordererOrganizations/magnetocorp.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

    OrdererEndpoints:
      - "127.0.0.1:7050"

  - &MagnetoCorp
    Name: MagnetoCorp
    ID: MagnetoCorpMSP
    MSPDir: ../artifacts/crypto-config/peerOrganizations/magnetocorp.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MagnetoCorpMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('MagnetoCorpMSP.admin', 'MagnetoCorpMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MagnetoCorpMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MagnetoCorpMSP.peer')"

  - &DigiBank
    Name: DigiBank
    ID: DigiBankMSP
    MSPDir: ../artifacts/crypto-config/peerOrganizations/digibank.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DigiBankMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('DigiBankMSP.admin', 'DigiBankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DigiBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DigiBankMSP.peer')"

################################################################################
#
#   CAPABILITIES
#
#   This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

################################################################################
#
#   ORDERER
#
#   This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters.
#
################################################################################
Orderer: &OrdererDefaults
  OrdererType: solo
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 45 MB
    PreferredMaxBytes: 512 KB
  
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *OrdererCapabilities


################################################################################
#
#   APPLICATION
#
#   This section defines the values to encode into a config transaction or
#   genesis block for application-related parameters.
#
################################################################################
Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

################################################################################
#
#   PROFILES
#
#   Different configuration profiles may be encoded here to be specified as
#   parameters to the configtxgen tool. The profiles which specify consortiums
#   are to be used for generating the orderer genesis block. With the correct
#   consortium members defined in the orderer genesis block, channel creation
#   requests may be generated with only the org member names and a consortium
#   name.
#
################################################################################
Profiles:
  MagnetoCorpOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Orderer
    Consortiums:
      PapernetConsortium:
        Organizations:
          - *MagnetoCorp

  MagnetoCorpChannel:
    <<: *ChannelDefaults
    Consortium: PapernetConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *MagnetoCorp

  PapernetChannel:
    <<: *ChannelDefaults
    Consortium: PapernetConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *MagnetoCorp
        - *DigiBank
