PeerOrgs:
  - Name: MagnetoCorp
    Domain: magnetocorp.com
    EnableNodeOUs: true
    Specs:
      - Hostname: magnetocorp-dev-peer
        CommonName: magnetocorp-dev-peer
        SANS:
          - 127.0.0.1
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: DigiBank 
    Domain: digibank.com
    EnableNodeOUs: true
    Specs:
      - Hostname: digibank-dev-peer
        CommonName: digibank-dev-peer
    Template:
      Count: 2
    Users:
      Count: 2